-- Limpieza inicial
DROP TABLE IF EXISTS control_cashback;
DROP TABLE IF EXISTS transacciones;
DROP TABLE IF EXISTS deudas;
DROP TABLE IF EXISTS cuentas;
DROP TABLE IF EXISTS categorias;

-- 1. Categorias
CREATE TABLE categorias (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria VARCHAR(50) NOT NULL,
    nombre_subcategoria VARCHAR(50) NOT NULL,
    UNIQUE(nombre_categoria, nombre_subcategoria) 
);

-- 2. Cuentas
CREATE TABLE cuentas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL, 
    tipo VARCHAR(20) NOT NULL, 
    saldo_inicial DECIMAL(12, 2) DEFAULT 0.00
);

-- 3. Deudas
CREATE TABLE deudas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL, 
    monto_total DECIMAL(12, 2) NOT NULL,
    monto_restante DECIMAL(12, 2) NOT NULL,
    fecha_inicio DATE DEFAULT CURRENT_DATE,
    id_cuenta_asociada INTEGER REFERENCES cuentas(id) ON DELETE SET NULL
);

-- 4. Transacciones
CREATE TABLE transacciones (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    monto DECIMAL(12, 2) NOT NULL, 
    descripcion VARCHAR(255),
    id_cuenta INTEGER NOT NULL REFERENCES cuentas(id) ON DELETE CASCADE,
    id_categoria INTEGER REFERENCES categorias(id),
    id_deuda INTEGER REFERENCES deudas(id)
);

-- 5. Control Cashback
CREATE TABLE control_cashback (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_compra DATE DEFAULT CURRENT_DATE,
    descripcion VARCHAR(255),
    monto DECIMAL(12, 2) NOT NULL,
    estado VARCHAR(20) DEFAULT 'Pendiente',
    id_cuenta INTEGER REFERENCES cuentas(id) ON DELETE SET NULL
);